### ISSUE TITLE
preprocess dir make has no error, but when run exp.py got  attributeError

### ISSUE THREAD

**Issue by visonpon** [intel-isl/StableViewSynthesis#1]
Hi, @dvdhfnr
Thanks for your great work and when I try to test I got an error like the below:
`AttributeError: module 'ext.preprocess' has no attribute 'map_source_points'`
hope you can help, thanks~

**Comment by Kait0** [comment]
Hi, I have the same error. Can you share your solution?

**Comment by Kait0** [comment]
Fixed it as well by now. The problem was in my case that the compiled preprocess.cp37-win_amd64.pyd (etc. file) were in a folder that the python __init__ did not find. Copying them to ...\StableViewSynthesis\ext\preprocess solved the issue.
