### ISSUE TITLE
What's the value of M in test/validation phase?

### ISSUE THREAD

**Issue by 07hyx06** [intel-isl/StableViewSynthesis#2]
Hi!
I am really interested in your work but I have little time to read the code. I have two questions about the evaluation Section in the paper.
1) How to select M=3 source views in one training pass? Randomly picked?
2) What's the value of M and how to select it in test/validation phase? Just send all of the source views into the network?

**Comment by griegler** [comment]
Ad 1) Yes, they are randomly sampled, but with with probability based on the overlap to the target image.
Ad 2) In the evaluation I use (mainly for memory reasons) max 5 views per 3D point.
