### ISSUE TITLE
'pybind11' not exist.. 

### ISSUE THREAD

**Issue by bring728** [intel-isl/StableViewSynthesis#3]
cmake -DCMAKE_BUILD_TYPE=Release .

-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'eigen3'
--   Found eigen3, version 3.3.4
CMake Error at CMakeLists.txt:10 (add_subdirectory):
  add_subdirectory given source "pybind11" which is not an existing
  directory.

CMake Error at CMakeLists.txt:12 (pybind11_add_module):
  Unknown CMake command "pybind11_add_module".

-- Configuring incomplete, errors occurred!

in ubuntu 18.04 i got this error message during Cmake, can you help me?

**Comment by BingEdison** [comment]
I encountered same error , try below recommendation

go here https://github.com/pybind/pybind11

and put into preprocess folder 

$/StableViewSynthesis/ext/preprocess/

**Comment by bring728** [comment]
Wow! It worked! Thank you very much. god bless you!

**Comment by griegler** [comment]
Thanks. Somehow the .gitmodules files got lost in the release. I pushed it, now the instructions should work as intended.

**Comment by Leon-1126** [comment]
> try below recommendation, worked for me
> 
> go here https://github.com/pybind/pybind11
> 
> git clone into preprocess folder
> 
> $/StableViewSynthesis/ext/preprocess/

Wow, I hit the same question, thank you very much !
