### ISSUE TITLE
Failure to run exp.py

### ISSUE THREAD

**Issue by grgkopanas** [intel-isl/StableViewSynthesis#6]
Seems like the torch_scatter is expecting a pretty old version of PyTorch, is that expected?

```
(stableviewsynthesis) [gkopanas@nefgpu34 experiments]$ python exp.py --net resunet3.16_penone.dirs.avg.seq+9+1+unet+5+2+16.single+mlpdir+mean+3+64+16 --cmd eval --iter last --eval-dsets tat-subseq
Traceback (most recent call last):
  File "/home/gkopanas/.conda/envs/stableviewsynthesis/lib/python3.7/site-packages/torch_scatter/__init__.py", line 13, in <module>
    library, [osp.dirname(__file__)]).origin)
  File "/home/gkopanas/.conda/envs/stableviewsynthesis/lib/python3.7/site-packages/torch/_ops.py", line 104, in load_library
    ctypes.CDLL(path)
  File "/home/gkopanas/.conda/envs/stableviewsynthesis/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/gkopanas/.conda/envs/stableviewsynthesis/lib/python3.7/site-packages/torch_scatter/_version.so: undefined symbol: _ZN3c1017RegisterOperatorsC1Ev

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "exp.py", line 10, in <module>
    import modules
  File "/home/gkopanas/StableViewSynthesis/experiments/modules.py", line 8, in <module>
    import torch_scatter
  File "/home/gkopanas/.conda/envs/stableviewsynthesis/lib/python3.7/site-packages/torch_scatter/__init__.py", line 19, in <module>
    f'Expected PyTorch version {t_major}.{t_minor} but found '
RuntimeError: Expected PyTorch version 1.4 but found version 1.8.
```

my conda packages are the following:
```
# packages in environment at /home/gkopanas/.conda/envs/stableviewsynthesis:
#
_libgcc_mutex             0.1                        main
argon2-cffi               20.1.0           py37h27cfd23_1
ase                       3.21.1             pyhd8ed1ab_0    conda-forge
async_generator           1.10               pyhd3eb1b0_0
attrs                     20.3.0             pyhd3eb1b0_0
backcall                  0.2.0              pyhd3eb1b0_0
blas                      1.0                         mkl
bleach                    3.3.0              pyhd3eb1b0_0
blosc                     1.21.0               h8c45485_0
brotli                    1.0.9                he6710b0_2
brotlipy                  0.7.0           py37hb5d75c8_1001    conda-forge
brunsli                   0.1                  h2531618_0
bzip2                     1.0.8                h7b6447c_0
ca-certificates           2021.1.19            h06a4308_1
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
certifi                   2020.12.5        py37h06a4308_0
cffi                      1.14.5           py37h261ae71_0
chardet                   4.0.0            py37h89c1867_1    conda-forge
charls                    2.1.0                he6710b0_2
click                     7.1.2              pyh9f0ad1d_0    conda-forge
cloudpickle               1.6.0                      py_0
cryptography              3.4.6            py37h5d9358c_0    conda-forge
cudatoolkit               10.2.89              hfd86e86_1
cycler                    0.10.0                     py_2    conda-forge
cytoolz                   0.11.0           py37h7b6447c_0
dask-core                 2021.3.0           pyhd3eb1b0_0
dbus                      1.13.18              hb2f20db_0
decorator                 4.4.2                      py_0    conda-forge
defusedxml                0.7.1              pyhd3eb1b0_0
entrypoints               0.3                      py37_0
expat                     2.2.10               he6710b0_2
ffmpeg                    4.3                  hf484d3e_0    pytorch
flask                     1.1.2              pyh9f0ad1d_0    conda-forge
fontconfig                2.13.1               h6c09931_0
freetype                  2.10.4               h5ab3b9f_0
giflib                    5.1.4                h14c3975_1
glib                      2.67.4               h36276a3_1
gmp                       6.2.1                h2531618_2
gnutls                    3.6.5             h71b1129_1002
googledrivedownloader     0.4                pyh9f0ad1d_0    conda-forge
gst-plugins-base          1.14.0               h8213a91_2
gstreamer                 1.14.0               h28cd5cc_2
h5py                      3.1.0           nompi_py37h1e651dc_100    conda-forge
hdf5                      1.10.6          nompi_h3c11f04_101    conda-forge
html5lib                  1.1                pyh9f0ad1d_0    conda-forge
icu                       58.2                 he6710b0_3
idna                      2.10               pyh9f0ad1d_0    conda-forge
imagecodecs               2021.1.11        py37h581e88b_1
imageio                   2.9.0                      py_0
importlib-metadata        2.0.0                      py_1
importlib_metadata        2.0.0                         1
intel-openmp              2020.2                      254
ipykernel                 5.3.4            py37h5ca1d4c_0
ipython                   7.21.0           py37hb070fc8_0
ipython_genutils          0.2.0              pyhd3eb1b0_1
ipywidgets                7.6.3              pyhd3eb1b0_1
isodate                   0.6.0                      py_1    conda-forge
itsdangerous              1.1.0                      py_0    conda-forge
jedi                      0.17.0                   py37_0
jinja2                    2.11.3             pyh44b312d_0    conda-forge
joblib                    1.0.1              pyhd8ed1ab_0    conda-forge
jpeg                      9b                   h024ee3a_2
jsonschema                3.2.0                      py_2
jupyter_client            6.1.7                      py_0
jupyter_core              4.7.1            py37h06a4308_0
jupyterlab_pygments       0.1.2                      py_0
jupyterlab_widgets        1.0.0              pyhd3eb1b0_1
jxrlib                    1.1                  h7b6447c_2
keepalive                 0.5              py37h89c1867_5    conda-forge
kiwisolver                1.3.1            py37hc928c03_0    conda-forge
lame                      3.100                h7b6447c_0
lcms2                     2.11                 h396b838_0
ld_impl_linux-64          2.33.1               h53a641e_7
lerc                      2.2.1                h2531618_0
libaec                    1.0.4                he6710b0_1
libblas                   3.9.0                8_openblas    conda-forge
libcblas                  3.9.0                8_openblas    conda-forge
libdeflate                1.7                  h27cfd23_5
libedit                   3.1.20191231         h14c3975_1
libffi                    3.3                  he6710b0_2
libgcc-ng                 9.1.0                hdf63c60_0
libgfortran-ng            7.3.0                hdf63c60_0
libgfortran4              7.5.0               h14aa051_18    conda-forge
libiconv                  1.15                 h63c8f33_5
libllvm10                 10.0.1               he513fc3_3    conda-forge
libopenblas               0.3.12          pthreads_hb3c22a3_1    conda-forge
libpng                    1.6.37               hbc83047_0
libsodium                 1.0.18               h7b6447c_0
libstdcxx-ng              9.1.0                hdf63c60_0
libtiff                   4.2.0                h3942068_0
libuuid                   1.0.3                h1bed415_2
libuv                     1.40.0               h7b6447c_0
libwebp                   1.0.1                h8e7db2f_0
libwebp-base              1.2.0                h27cfd23_0
libxcb                    1.14                 h7b6447c_0
libxml2                   2.9.10               hb55368b_3
libzopfli                 1.0.3                he6710b0_0
llvmlite                  0.34.0           py37h5202443_2    conda-forge
lz4-c                     1.9.3                h2531618_0
markupsafe                1.1.1            py37hb5d75c8_2    conda-forge
matplotlib                3.3.4            py37h06a4308_0
matplotlib-base           3.3.4            py37h62a2d02_0
mistune                   0.8.4           py37h14c3975_1001
mkl                       2020.2                      256
mkl-service               2.3.0            py37he8ac12f_0
mkl_fft                   1.3.0            py37h54f3939_0
mkl_random                1.1.1            py37h0573a6f_0
nbclient                  0.5.3              pyhd3eb1b0_0
nbconvert                 6.0.7                    py37_0
nbformat                  5.1.2              pyhd3eb1b0_1
ncurses                   6.2                  he6710b0_1
nest-asyncio              1.5.1              pyhd3eb1b0_0
nettle                    3.4.1                hbb512f6_0
networkx                  2.5                        py_0    conda-forge
ninja                     1.10.2           py37hff7bd54_0
notebook                  6.2.0            py37h06a4308_0
numba                     0.51.2           py37h9fdb41a_0    conda-forge
numpy                     1.19.2           py37h54aff64_0
numpy-base                1.19.2           py37hfa32c7d_0
olefile                   0.46                       py_0
open3d                    0.11.2                   py37_0    open3d-admin
openh264                  2.1.0                hd408876_0
openjpeg                  2.3.0                h05c96fa_1
openssl                   1.1.1j               h27cfd23_0
packaging                 20.9               pyhd3eb1b0_0
pandas                    1.2.3            py37ha9443f7_0
pandoc                    2.11                 hb0f4dca_0
pandocfilters             1.4.3            py37h06a4308_1
parso                     0.8.1              pyhd3eb1b0_0
pcre                      8.44                 he6710b0_0
pexpect                   4.8.0              pyhd3eb1b0_3
pickleshare               0.7.5           pyhd3eb1b0_1003
pillow                    8.1.2            py37he98fc37_0
pip                       21.0.1           py37h06a4308_0
plyfile                   0.7.3              pyh44b312d_0    conda-forge
prometheus_client         0.9.0              pyhd3eb1b0_0
prompt-toolkit            3.0.8                      py_0
ptyprocess                0.7.0              pyhd3eb1b0_2
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pygments                  2.8.1              pyhd3eb1b0_0
pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyqt                      5.9.2            py37h05f1152_2
pyrsistent                0.17.3           py37h7b6447c_0
pysocks                   1.7.1            py37h89c1867_3    conda-forge
python                    3.7.10               hdb3f193_0
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.7                     1_cp37m    conda-forge
pytorch                   1.8.0           py3.7_cuda10.2_cudnn7.6.5_0    pytorch
pytorch_cluster           1.5.4            py37hcae2be3_1    conda-forge
pytorch_geometric         1.6.1              pyh9f0ad1d_0    conda-forge
pytorch_scatter           2.0.4            py37hcae2be3_1    conda-forge
pytorch_sparse            0.6.3            py37hcae2be3_1    conda-forge
pytorch_spline_conv       1.2.0            py37hcae2be3_1    conda-forge
pytz                      2021.1             pyhd8ed1ab_0    conda-forge
pywavelets                1.1.1            py37h7b6447c_2
pyyaml                    5.4.1            py37h27cfd23_1
pyzmq                     20.0.0           py37h2531618_1
qt                        5.9.7                h5867ecd_1
rdflib                    5.0.0            py37h89c1867_3    conda-forge
readline                  8.1                  h27cfd23_0
requests                  2.25.1             pyhd3deb0d_0    conda-forge
scikit-image              0.17.2           py37hdf5156a_0
scikit-learn              0.23.2           py37hddcf8d6_3    conda-forge
scipy                     1.6.1            py37h91f5cce_0
send2trash                1.5.0              pyhd3eb1b0_1
setuptools                52.0.0           py37h06a4308_0
sip                       4.19.8           py37hf484d3e_0
six                       1.15.0             pyhd3eb1b0_0
snappy                    1.1.8                he6710b0_0
sparqlwrapper             1.8.5           py37h89c1867_1005    conda-forge
sqlite                    3.33.0               h62c20be_0
terminado                 0.9.2            py37h06a4308_0
testpath                  0.4.4              pyhd3eb1b0_0
threadpoolctl             2.1.0              pyh5ca1d4c_0    conda-forge
tifffile                  2021.3.5           pyhd3eb1b0_1
tk                        8.6.10               hbc83047_0
toolz                     0.11.1             pyhd3eb1b0_0
torchaudio                0.8.0                      py37    pytorch
torchvision               0.9.0                py37_cu102    pytorch
tornado                   6.1              py37h4abf009_0    conda-forge
tqdm                      4.59.0             pyhd8ed1ab_0    conda-forge
traitlets                 5.0.5              pyhd3eb1b0_0
typing_extensions         3.7.4.3            pyha847dfd_0
urllib3                   1.26.3             pyhd8ed1ab_0    conda-forge
wcwidth                   0.2.5                      py_0
webencodings              0.5.1                      py_1    conda-forge
werkzeug                  1.0.1              pyh9f0ad1d_0    conda-forge
wheel                     0.36.2             pyhd3eb1b0_0
widgetsnbextension        3.5.1                    py37_0
xz                        5.2.5                h7b6447c_0
yaml                      0.2.5                h7b6447c_0
zeromq                    4.3.3                he6710b0_3
zfp                       0.5.5                h2531618_4
zipp                      3.4.0              pyhd3eb1b0_0
zlib                      1.2.11               h7b6447c_3
zstd                      1.4.5                h9ceee32_0
```

**Comment by BingEdison** [comment]
try switching to older pytorch. Below dependencies have worked in conda 

# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
argon2-cffi               20.1.0                   pypi_0    pypi
ase                       3.21.1                   pypi_0    pypi
async-generator           1.10                     pypi_0    pypi
attrs                     20.3.0                   pypi_0    pypi
backcall                  0.2.0                    pypi_0    pypi
blas                      1.0                         mkl  
bleach                    3.3.0                    pypi_0    pypi
ca-certificates           2021.1.19            h06a4308_0  
cached-property           1.5.2                    pypi_0    pypi
certifi                   2020.12.5        py37h89c1867_1    conda-forge
cffi                      1.14.5                   pypi_0    pypi
chardet                   4.0.0                    pypi_0    pypi
cmaketools                0.1.6                    pypi_0    pypi
cudatoolkit               10.1.243             h6bb024c_0  
cycler                    0.10.0                   pypi_0    pypi
decorator                 4.4.2                    pypi_0    pypi
defusedxml                0.6.0                    pypi_0    pypi
entrypoints               0.3                      pypi_0    pypi
freetype                  2.10.4               h5ab3b9f_0  
future                    0.18.2                   pypi_0    pypi
googledrivedownloader     0.4                      pypi_0    pypi
h5py                      3.1.0                    pypi_0    pypi
idna                      2.10                     pypi_0    pypi
imageio                   2.9.0                    pypi_0    pypi
importlib-metadata        3.4.0                    pypi_0    pypi
intel-openmp              2020.2                      254  
ipykernel                 5.5.0                    pypi_0    pypi
ipython                   7.20.0                   pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
ipywidgets                7.6.3                    pypi_0    pypi
isodate                   0.6.0                    pypi_0    pypi
jedi                      0.18.0                   pypi_0    pypi
jinja2                    2.11.3                   pypi_0    pypi
joblib                    1.0.1                    pypi_0    pypi
jpeg                      9b                   h024ee3a_2  
jsonschema                3.2.0                    pypi_0    pypi
jupyter-client            6.1.11                   pypi_0    pypi
jupyter-core              4.7.1                    pypi_0    pypi
jupyterlab-pygments       0.1.2                    pypi_0    pypi
jupyterlab-widgets        1.0.0                    pypi_0    pypi
kiwisolver                1.3.1                    pypi_0    pypi
lcms2                     2.11                 h396b838_0  
ld_impl_linux-64          2.33.1               h53a641e_7  
libedit                   3.1.20191231         h14c3975_1  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.1.0                hdf63c60_0  
libpng                    1.6.37               hbc83047_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.1.0                h2733197_1  
llvmlite                  0.35.0                   pypi_0    pypi
lz4-c                     1.9.3                h2531618_0  
markupsafe                1.1.1                    pypi_0    pypi
matplotlib                3.2.0                    pypi_0    pypi
mistune                   0.8.4                    pypi_0    pypi
mkl                       2020.2                      256  
mkl-service               2.3.0            py37he8ac12f_0  
mkl_fft                   1.2.1            py37h54f3939_0  
mkl_random                1.1.1            py37h0573a6f_0  
nbclient                  0.5.2                    pypi_0    pypi
nbconvert                 6.0.7                    pypi_0    pypi
nbformat                  5.1.2                    pypi_0    pypi
ncurses                   6.2                  he6710b0_1  
nest-asyncio              1.5.1                    pypi_0    pypi
networkx                  2.5                      pypi_0    pypi
ninja                     1.10.0.post2             pypi_0    pypi
notebook                  6.2.0                    pypi_0    pypi
numba                     0.52.0                   pypi_0    pypi
numpy                     1.19.0                   pypi_0    pypi
numpy-base                1.19.2           py37hfa32c7d_0  
olefile                   0.46                     py37_0  
open3d                    0.11.0                   pypi_0    pypi
opencv-python             4.5.1.48                 pypi_0    pypi
openssl                   1.1.1j               h27cfd23_0  
packaging                 20.9                     pypi_0    pypi
pandas                    1.0.0                    pypi_0    pypi
pandocfilters             1.4.3                    pypi_0    pypi
parso                     0.8.1                    pypi_0    pypi
pexpect                   4.8.0                    pypi_0    pypi
pickleshare               0.7.5                    pypi_0    pypi
pillow                    7.2.0                    pypi_0    pypi
pip                       21.0.1           py37h06a4308_0  
prometheus-client         0.9.0                    pypi_0    pypi
prompt-toolkit            3.0.16                   pypi_0    pypi
ptyprocess                0.7.0                    pypi_0    pypi
pybind11                  2.6.1            py37hc928c03_0    conda-forge
pybind11-global           2.6.1                    pypi_0    pypi
pycparser                 2.20                     pypi_0    pypi
pygments                  2.8.0                    pypi_0    pypi
pyparsing                 2.4.7                    pypi_0    pypi
pyrsistent                0.17.3                   pypi_0    pypi
python                    3.7.9                h7579374_0  
python-dateutil           2.8.1                    pypi_0    pypi
python-louvain            0.15                     pypi_0    pypi
python_abi                3.7                     1_cp37m    conda-forge
pytorch                   1.6.0           py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch
pytz                      2021.1                   pypi_0    pypi
pywavelets                1.1.1                    pypi_0    pypi
pyzmq                     22.0.3                   pypi_0    pypi
rdflib                    5.0.0                    pypi_0    pypi
readline                  8.1                  h27cfd23_0  
requests                  2.25.1                   pypi_0    pypi
scikit-image              0.15.0                   pypi_0    pypi
scikit-learn              0.24.1                   pypi_0    pypi
scipy                     1.6.1                    pypi_0    pypi
send2trash                1.5.0                    pypi_0    pypi
setuptools                52.0.0           py37h06a4308_0  
six                       1.15.0           py37h06a4308_0  
sqlite                    3.33.0               h62c20be_0  
terminado                 0.9.2                    pypi_0    pypi
testpath                  0.4.4                    pypi_0    pypi
threadpoolctl             2.1.0                    pypi_0    pypi
tifffile                  2021.2.1                 pypi_0    pypi
tk                        8.6.10               hbc83047_0  
torch-geometric           1.6.3                    pypi_0    pypi
torch-scatter             2.0.2                    pypi_0    pypi
torch-sparse              0.6.0                    pypi_0    pypi
torchvision               0.7.0                    pypi_0    pypi
tornado                   6.1                      pypi_0    pypi
tqdm                      4.57.0                   pypi_0    pypi
traitlets                 5.0.5                    pypi_0    pypi
typing-extensions         3.7.4.3                  pypi_0    pypi
urllib3                   1.26.3                   pypi_0    pypi
wcwidth                   0.2.5                    pypi_0    pypi
webencodings              0.5.1                    pypi_0    pypi
wheel                     0.36.2             pyhd3eb1b0_0  
widgetsnbextension        3.5.1                    pypi_0    pypi
xz                        5.2.5                h7b6447c_0  
zipp                      3.4.0                    pypi_0    pypi
zlib                      1.2.11               h7b6447c_3  
zstd                      1.4.5                h9ceee32_0

**Comment by grgkopanas** [comment]
Thanks for the help, the problem was with how conda resolves the exact package binary for the correct pytorch version of torch-scatter.

To work-around the problem I used pip install and fixed the appropriate version on the wheel link:

```
!pip install -q torch-scatter -f https://pytorch-geometric.com/whl/torch-1.6.0+cu101.html
!pip install -q torch-sparse -f https://pytorch-geometric.com/whl/torch-1.6.0+cu101.html
!pip install -q torch-geometric
```

All the best,
George
